name: Publish Docker image to UHub
on:
  push:
    branches: [master]
jobs:
  push_to_registry:
    name: Push Docker image to UHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to UHub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.UHUB_USERNAME }}
          password: ${{ secrets.UHUB_PASSWORD }}
          registry: uhub.service.ucloud.cn 
          repository: likecoding/wetty
          tag_with_ref: true
